//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityprosedürler2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GorevEntities : DbContext
    {
        public GorevEntities()
            : base("name=GorevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Elemanlar> Elemanlar { get; set; }
        public virtual DbSet<Gorevler> Gorevler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<Eara_Result> Eara(string ara)
        {
            var araParameter = ara != null ?
                new ObjectParameter("ara", ara) :
                new ObjectParameter("ara", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Eara_Result>("Eara", araParameter);
        }
    
        public virtual int Eekle(string a1, string a2, Nullable<decimal> a3, string a4, Nullable<int> a5)
        {
            var a1Parameter = a1 != null ?
                new ObjectParameter("a1", a1) :
                new ObjectParameter("a1", typeof(string));
    
            var a2Parameter = a2 != null ?
                new ObjectParameter("a2", a2) :
                new ObjectParameter("a2", typeof(string));
    
            var a3Parameter = a3.HasValue ?
                new ObjectParameter("a3", a3) :
                new ObjectParameter("a3", typeof(decimal));
    
            var a4Parameter = a4 != null ?
                new ObjectParameter("a4", a4) :
                new ObjectParameter("a4", typeof(string));
    
            var a5Parameter = a5.HasValue ?
                new ObjectParameter("a5", a5) :
                new ObjectParameter("a5", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eekle", a1Parameter, a2Parameter, a3Parameter, a4Parameter, a5Parameter);
        }
    
        public virtual ObjectResult<Elistele_Result> Elistele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Elistele_Result>("Elistele");
        }
    
        public virtual ObjectResult<Emaassirala_Result> Emaassirala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Emaassirala_Result>("Emaassirala");
        }
    
        public virtual int Esil(Nullable<int> elemanNo)
        {
            var elemanNoParameter = elemanNo.HasValue ?
                new ObjectParameter("ElemanNo", elemanNo) :
                new ObjectParameter("ElemanNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Esil", elemanNoParameter);
        }
    
        public virtual int Eyenile(Nullable<int> elemanNo, string elemanAdi, string elemanPozisyon, Nullable<decimal> elemanMaas, string elemanStatu, Nullable<int> gorevNo)
        {
            var elemanNoParameter = elemanNo.HasValue ?
                new ObjectParameter("ElemanNo", elemanNo) :
                new ObjectParameter("ElemanNo", typeof(int));
    
            var elemanAdiParameter = elemanAdi != null ?
                new ObjectParameter("ElemanAdi", elemanAdi) :
                new ObjectParameter("ElemanAdi", typeof(string));
    
            var elemanPozisyonParameter = elemanPozisyon != null ?
                new ObjectParameter("ElemanPozisyon", elemanPozisyon) :
                new ObjectParameter("ElemanPozisyon", typeof(string));
    
            var elemanMaasParameter = elemanMaas.HasValue ?
                new ObjectParameter("ElemanMaas", elemanMaas) :
                new ObjectParameter("ElemanMaas", typeof(decimal));
    
            var elemanStatuParameter = elemanStatu != null ?
                new ObjectParameter("ElemanStatu", elemanStatu) :
                new ObjectParameter("ElemanStatu", typeof(string));
    
            var gorevNoParameter = gorevNo.HasValue ?
                new ObjectParameter("GorevNo", gorevNo) :
                new ObjectParameter("GorevNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Eyenile", elemanNoParameter, elemanAdiParameter, elemanPozisyonParameter, elemanMaasParameter, elemanStatuParameter, gorevNoParameter);
        }
    
        public virtual ObjectResult<Garama_Result> Garama(string p1)
        {
            var p1Parameter = p1 != null ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Garama_Result>("Garama", p1Parameter);
        }
    
        public virtual int Gekle(string p1, string p2, string p3, Nullable<int> p4, string p5)
        {
            var p1Parameter = p1 != null ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(string));
    
            var p2Parameter = p2 != null ?
                new ObjectParameter("p2", p2) :
                new ObjectParameter("p2", typeof(string));
    
            var p3Parameter = p3 != null ?
                new ObjectParameter("p3", p3) :
                new ObjectParameter("p3", typeof(string));
    
            var p4Parameter = p4.HasValue ?
                new ObjectParameter("p4", p4) :
                new ObjectParameter("p4", typeof(int));
    
            var p5Parameter = p5 != null ?
                new ObjectParameter("p5", p5) :
                new ObjectParameter("p5", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Gekle", p1Parameter, p2Parameter, p3Parameter, p4Parameter, p5Parameter);
        }
    
        public virtual ObjectResult<Glistele_Result> Glistele()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Glistele_Result>("Glistele");
        }
    
        public virtual int Gsil(Nullable<int> p1)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Gsil", p1Parameter);
        }
    
        public virtual ObjectResult<Gsirala_Result> Gsirala()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Gsirala_Result>("Gsirala");
        }
    
        public virtual int Gyenile(Nullable<int> p1, string p2, string p3, string p4, Nullable<int> p5, string p6)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(int));
    
            var p2Parameter = p2 != null ?
                new ObjectParameter("p2", p2) :
                new ObjectParameter("p2", typeof(string));
    
            var p3Parameter = p3 != null ?
                new ObjectParameter("p3", p3) :
                new ObjectParameter("p3", typeof(string));
    
            var p4Parameter = p4 != null ?
                new ObjectParameter("p4", p4) :
                new ObjectParameter("p4", typeof(string));
    
            var p5Parameter = p5.HasValue ?
                new ObjectParameter("p5", p5) :
                new ObjectParameter("p5", typeof(int));
    
            var p6Parameter = p6 != null ?
                new ObjectParameter("p6", p6) :
                new ObjectParameter("p6", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Gyenile", p1Parameter, p2Parameter, p3Parameter, p4Parameter, p5Parameter, p6Parameter);
        }
    
        public virtual ObjectResult<join1_Result> join1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<join1_Result>("join1");
        }
    
        public virtual ObjectResult<join2_Result> join2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<join2_Result>("join2");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
